### ISSUE TITLE
Plugin manager as modal window over GitExtensions

### ISSUE THREAD

**Issue by maraf** [gitextensions/gitextensions.pluginmanager#13]
As suggested in #4 and #5, make PM a modal window.

**Comment by maraf** [comment]
How PM should behave when user has 2 instances of GE opened and starts PM from both?

**Comment by mast-eu** [comment]
> How PM should behave when user has 2 instances of GE opened and starts PM from both?

We should avoid multiple PM instances which could install/update/remove plugins in concurrency. 

IMHO a simple popup `Another instance of PluginManager is already running` would be perfect. 
Can we achieve this?

**Comment by maraf** [comment]
> IMHO a simple popup Another instance of PluginManager is already running would be perfect.
Can we achieve this?

Yes. We can even active / bring to front the already running instance.
