### ISSUE TITLE
GE.PM is not loaded when placed in \AppData\Local\GitExtensions\UserPlugins\

### ISSUE THREAD

**Issue by mast-eu** [gitextensions/gitextensions.pluginmanager#15]
GE.PM runs as expected when placed in `<GE_rootDir>\UserPlugins\*`, which is the default location for plugins in GE portable.

However, GE.PM does not run when placed in `<user_name>\AppData\Local\GitExtensions\UserPlugins\*`, which is the default location for plugins in GE installed version.
I checked with the debugger that GE finds the file `<user_name>\AppData\Local\GitExtensions\UserPlugins\GitExtensions.PluginManager.dll`, but for some reason the plugin is not loaded correctly.

@maraf: Can you confirm this observation, or do I miss something?

**Comment by maraf** [comment]
@mast-eu On my testing machine it seems that I'm not able to load any of user plugins in installed-mode. But it's a virtual machine and I don't have debugger there, tomorrow I'm going to dig a bit deeper.

**Comment by maraf** [comment]
@mast-eu I tried to download latest portable version from AppVeyor, changed parameter `IsPortable` to `true` in GE.config file and UserPlugins works (both empty and PM from AppVeyor).

**Comment by mast-eu** [comment]
Thank you for indicating the piece I missed: `IsPortable` in `GitExtensions.exe.config`.

Setting `IsPortable=True` loads plugins from `<GE_rootDir>\UserPlugins\*`, while `IsPortable=False` loads plugins from `<user_name>\AppData\Local\GitExtensions\UserPlugins\*`. Makes sense.

**Comment by RussKie** [comment]
Worth noting that in the readme
