### ISSUE TITLE
Signing policy

### ISSUE THREAD

**Issue by mast-eu** [gitextensions/gitextensions.pluginmanager#17]
The PM builds are not yet signed (https://github.com/gitextensions/gitextensions.pluginmanager/pull/14#discussion_r291433369). 
We need to change this before including PM into GE's installer.

**Comment by RussKie** [comment]
I've been thinking of it - we will sign it when it is included into the package.

**Comment by mast-eu** [comment]
> we will sign it when it is included into the package.

This will work for a PM version bundled with GE's installer.
But what about a PM version that is released as NuGet package (i.e. not bundled to a GE version)?

**Comment by RussKie** [comment]
Ah, yes, it completely escaped me.
Once we have a build going and have an artifact name, I will hook up the signing

**Comment by maraf** [comment]
> Once we have a build going and have an artifact name

Build is up. I have noticed only that README badge points to the old AppVeyor project.

**Comment by mast-eu** [comment]
Maybe this is already clear to everyone, but I realised it only now: At the end we need have both CI artifacts (`.nupkg` and `.zip`) signed.

`.nupkg` artifact will be used as unbundled releases (= PM auto updates). 
PR https://github.com/gitextensions/gitextensions.pluginmanager/pull/22 considers only `.nupkg`, but auto updates will be deactivated for PM v1.0.0 (see https://github.com/gitextensions/gitextensions.pluginmanager/issues/20 / https://github.com/gitextensions/gitextensions.pluginmanager/pull/24). Therefore, signed `.nupkg` artifacts will not be needed immediately. 

Instead, what is really used for bundled releases are the `.zip` artifacts (see https://github.com/gitextensions/gitextensions/pull/6664).
Here's how it works: [gitextensions/Setup/Prepare-Release.ps1](https://github.com/gitextensions/gitextensions/blob/7a994d7ef01235fcd5f6a0595c9eb0adf9b177ae/Setup/Prepare-Release.ps1#L153) calls [gitextensions/Setup/Download-PluginManager.ps1](https://github.com/gitextensions/gitextensions/blob/775d297e583625ea1098eed6e7b58f0f78d2e403/Setup/Download-PluginManager.ps1), in order to download and extract `gitextensions.pluginmanager/releases/GitExtensions.PluginManager.*.zip`. The archive's content is then included while building the installer.
At some point in this chain the binaries should get signed. One possibility is to sign them directly in the zip artifact, before uploading it to `gitextensions.pluginmanager/releases`. The other option, [as RussKie said](https://github.com/gitextensions/gitextensions.pluginmanager/issues/17#issuecomment-508458818), is to sign them while building the installer.

**Comment by RussKie** [comment]
We can sign both artifacts without problems.

However we will need to bundle any artifacts we wish to sign together (like [we do in GE](https://github.com/gitextensions/gitextensions/blob/release/3.1/Build/Prepare-Artifacts.ps1#L34-L41))

On the SignPath end we'll need to enhance the policy to include all artifacts too (e.g. [GE policy](https://app.signpath.io/Web/7c19b2cf-90f7-4d15-9b12-1b615f7c18c4/ArtifactConfigurations/36b6947f-2b38-482a-baf6-b6083633b57b)).

Few thing to note: a release policy typically requires a manual approval, and signed artifacts must be manually downloaded.

**Comment by mast-eu** [comment]
> We can sign both artifacts without problems.
> 
> However we will need to bundle any artifacts we wish to sign together (like [we do in GE](https://github.com/gitextensions/gitextensions/blob/release/3.1/Build/Prepare-Artifacts.ps1#L34-L41))


👍 I had exactly the same thing in mind.
If it's ok for you, I can take care of this issue. At least regarding the changes on the AppVeyor side.

> On the SignPath end we'll need to enhance the policy to include all artifacts too (e.g. [GE policy](https://app.signpath.io/Web/7c19b2cf-90f7-4d15-9b12-1b615f7c18c4/ArtifactConfigurations/36b6947f-2b38-482a-baf6-b6083633b57b)).

I don't think I have sufficient rights to modify the artifact configuration on SignPath. I guess @RussKie will need to take care of this.

> Few thing to note: a release policy typically requires a manual approval, and signed artifacts must be manually downloaded.

For releases it's good to have a "human in the loop".

**Comment by mast-eu** [comment]
#25 has been merged into branch `release/1.0`, not in `master`.
