### ISSUE TITLE
Add GitHub Package Registry as second default feed

### ISSUE THREAD

**Issue by mast-eu** [gitextensions/gitextensions.pluginmanager#19]
This is necessary, since we plan to publish our own packages (including PM updates) on GitHub.

**Comment by maraf** [comment]
@mast-eu Do we already have the URL?

**Comment by mast-eu** [comment]
Should be `https://nuget.pkg.github.com/gitextensions/index.json`.

Source: https://help.github.com/en/articles/configuring-nuget-for-use-with-github-package-registry#installing-a-package

**Comment by mast-eu** [comment]
Thinking about the security concerns that emerged in https://github.com/gitextensions/gitextensions.pluginmanager/issues/20#issuecomment-509828258, it would be nice if all core plugins would be somehow marked and are updatable *only* through the GH package registry. Since this is under our control, we can easily avoid name conflicts.

On the other hand, community plugins can be updated through  *any* feed, with nuget.org being pre-configured. The user may add as many additional feeds as he likes, but than it is within his own responsibility to avoid/resolve potential conflicts with the same package being available on multiple feeds.

**Comment by maraf** [comment]
NuGet recently announced package signing, maybe it could help us somehow.

**Comment by maraf** [comment]
@mast-eu GH feed requires authentication. Is it configured by use or its default?

**Comment by mast-eu** [comment]
As I understand it, authentication is only needed for publishing or deleting a package (i.e. for write access), but not for read access.

**Comment by RussKie** [comment]
Have a look here - https://ci.appveyor.com/project/gitextensions/gitextensions-pluginmanager/settings/nuget

**Comment by mast-eu** [comment]
Remember to revert #24 when implementing this.

**Comment by mast-eu** [comment]
Closing as obsolete.

We decided to not to use GitHub Package Registry, because it requires authentication even for downloading packages.
We might re-evaluate this if the need for authentication gets removed.
