### ISSUE TITLE
Build pipeline

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions.pluginmanager#2]
The project must be hooked up to a build pipeline to build execute tests for incoming PRs and merge commits.

We use Appveyor for Git Extensions, it is preferred but it is not mandated. SignPath that we use for the codesigning integrated best with AppVeyor.

**Comment by mast-eu** [comment]
> We use Appveyor for Git Extensions, it is preferred but it is not mandated.

In general, I would like to reuse as much as possible from the main repo. No need to reinvent things, just for fun.
Only exception would be if the things currently in place in the main repo have major flaws and we decide to use this repo as a test field. But for AppVeyor I don't think that this is the case.

**Comment by maraf** [comment]
@RussKie I already used AppVeyor in the original repo. Is the AppVeyor project under GE account created?

By signing you mean this script [Sign-Artifacts.ps1](https://github.com/gitextensions/gitextensions/blob/master/Setup/Sign-Artifacts.ps1)? 
Should I refactor it be parameterized and used for both repositories or "just copy-paste" it here?

**Comment by RussKie** [comment]
Please have a look at the appveyor.yml and scripts in /Build folder in release/3.1 branch.
The signing procedure has recently changed, https://about.signpath.io/documentation/build-system-integration/#appveyor
