### ISSUE TITLE
Temporarily disable self update

### ISSUE THREAD

**Issue by maraf** [gitextensions/gitextensions.pluginmanager#20]

**Comment by mast-eu** [comment]
Do we need to actually disable something?
I thought the PM in the current state would simply look on nuget.org, wouldn't
find any new package and that's it.

Il mar 9 lug 2019, 19:11 Marek Fišera <notifications@github.com> ha scritto:

**Comment by maraf** [comment]
Plugin passes packageId to PM. If such package exists, PM could do self update.

**Comment by mast-eu** [comment]
So this is to avoid that someone else in the meantime is publishing a package with the same name on nuget.org and the PM automatically updates to something that hasn't been published from GE. Did I understand you correctly?

**Comment by maraf** [comment]
Yes, on any feed.
