### ISSUE TITLE
'flat' structure in directory UserPlugins

### ISSUE THREAD

**Issue by mast-eu** [gitextensions/gitextensions.pluginmanager#29]
Currently the PM extracts all packages (including itself) directly into the directory `UserPlugins`. The resulting structure is:
```
UserPlugins
    Package1.dll
    Package1.config
    Package2.dll
    Package2.config
    ...
```

This may easily lead to errors due to file name clashes.

The directory structure should be:
```
UserPlugins
    Package1
        Package1.dll
        Package1.config
    Package2
        Package2.dll
        Package2.config
    ...
```

**Comment by mast-eu** [comment]
I started working on a fix and would like to get it included already in version 1.0.0 for 2 reasons:
1. After inclusion of PM into a GE release it gets much messier to change things like default installation paths, without breaking someone's plugins.
2. Since the change affects also the location of PluginManager itself, it has an impact on https://github.com/gitextensions/gitextensions/pull/6664 (not yet merged, I would push in the required changes before merging).

Any thoughts?

**Comment by RussKie** [comment]
Please go ahead.
I'm delying the v3.2 release waiting for the PM.

**Comment by mast-eu** [comment]
Thank you. I should be able to fix this one, prepare a second RC (or directly the final version 1.0.0, depending on when #27 will be closed) and complete https://github.com/gitextensions/gitextensions/pull/6664 in a few days. Let's say next weekend at the latest.

**Comment by RussKie** [comment]
Sounds good
