### ISSUE TITLE
Published date from metadata not shown

### ISSUE THREAD

**Issue by mast-eu** [gitextensions/gitextensions.pluginmanager#34]
Seems like the publishing date from the package metadata is always missing?

![image](https://user-images.githubusercontent.com/46861028/65054509-f2d1a900-d96d-11e9-839c-01ae73a03683.png)

**Comment by maraf** [comment]
It seems that it's empty only on nuget.org feed.

![image](https://user-images.githubusercontent.com/10020471/65122303-e2164700-d9f0-11e9-81d7-f6572d893596.png)

**Comment by mast-eu** [comment]
Yes, another element that is not mandatory in the [search query results](https://docs.microsoft.com/en-us/nuget/api/search-query-service-resource#search-result) and nuget.org doesn't provide it.

I propose to either remove it or set to `N/A` when not available.

**Comment by maraf** [comment]
I think we can remove it.

**Comment by maraf** [comment]
What about emty values for other attributes (licence and project URL)?

**Comment by mast-eu** [comment]
> I think we can remove it.

Agree.

> What about emty values for other attributes (licence and project URL)?

I'd leave them, since they can be filled at least. I.e. our own packages will always contain both.

**Comment by maraf** [comment]
> I'd leave them, since they can be filled at least. I.e. our own packages will always contain both.

I was thinking about placeholder values, instead of blank.

**Comment by mast-eu** [comment]
> I was thinking about placeholder values, instead of blank.

`N/A` would be fine as placeholder in my opinion.
