### ISSUE TITLE
Add SourceLink to debug it more easily

### ISSUE THREAD

**Issue by pmiossec** [gitextensions/gitextensions.pluginmanager#41]
https://github.com/dotnet/sourcelink

Context: I have a crash using it inside the plugin dll and I don't know where is the problem. Using sourcelink would have been made easy to debug the code...

**Comment by mast-eu** [comment]
Sounds good :+1: 
Do you plan to work on a PR for this feature?

**Comment by pmiossec** [comment]
My todo list is already full. We'll see. I don't know anymore how to do it since that have been updated for .net core...

I've started to have a look to add it to the plugin template.

We'll see if I have some time to spend on it...

**Comment by RussKie** [comment]
> I don't know anymore how to do it since that have been updated for .net core...

I don't think it is: https://github.com/dotnet/sourcelink#prerequisites-for-net-projects

The main solution has been converted to SDK-style projects. And we will be converting to .NET Core soon(-ish) too.

**Comment by mast-eu** [comment]
Closing. SourceLink has been added to https://github.com/gitextensions/gitextensions.plugintemplate, so new plugins generated from there will inherit it.

It was discussed that SourceLink doesn't provide much value to PM itself (https://github.com/gitextensions/gitextensions.plugintemplate/pull/13#issuecomment-586008827).
