### ISSUE TITLE
Plugin settings disappeared from GE

### ISSUE THREAD

**Issue by maraf** [gitextensions/gitextensions.pluginmanager#42]
Based on changes from gitextensions/gitextensions#7164, we need to call base ctor with boolean parameter (true) from the [Plugin.cs](https://github.com/gitextensions/gitextensions.pluginmanager/blob/master/src/GitExtensions.PluginManager/Plugin.cs).

**Comment by mast-eu** [comment]
Good catch.
Do you plan to prepare a PR for it?

**Comment by maraf** [comment]
> Do you plan to prepare a PR for it?

Yes.
