### ISSUE TITLE
Incorrect wording

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions.pluginmanager#51]
I have a single instance of the app running, and with this the warning text is a bit off:
![image](https://user-images.githubusercontent.com/4403806/101236634-f09c6b80-3726-11eb-80f3-684ef9b01614.png)

Perhaps we should check how many instance of the app is actually running (by interrogating running processes?), and adjust the wording appropriately.

Also instead of "these applications" we should say "the application".

**Comment by maraf** [comment]
This message notifies about closing all Git Extensions instances, not Plugin Manager instances.
So we should use something like

"Plugin Manager is going to write to files that are holded by Git Extensions. ..."

**Comment by RussKie** [comment]
Thank you for reminding me the PM is used outside GE.

In case of GE the message looks strange, and that was the motivator for the
issue and the PR.

Do we have a way to know how the PM was launched?

If a user runs the PM outside GE, and tries to update a GE plugin - what
would be the actual and expected behaviours?

PS: And it is "held" not "holded" :)

**Comment by maraf** [comment]
> Do we have a way to know how the PM was launched?

We do not, but we know names of processes to kill. We may use them in message.

> PS: And it is "held" not "holded" :)

Good catch. As you might notice, my English is far from perfect 😢

**Comment by RussKie** [comment]
> > Do we have a way to know how the PM was launched?
> 
> We do not, but we know names of processes to kill. We may use them in message.

Would you be able to do this?

> > PS: And it is "held" not "holded" :)
> 
> Good catch. As you might notice, my English is far from perfect 😢

Haha, mine too, so don't stress about it.
