### ISSUE TITLE
Can't see installed plugin info

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions.pluginmanager#53]
## Current behaviour:

Searching / installing a new plugin:
![image](https://user-images.githubusercontent.com/4403806/101236957-23476380-3729-11eb-8eba-a29bae5eac0b.png)

Installed plugin:
![image](https://user-images.githubusercontent.com/4403806/101236924-0a3eb280-3729-11eb-8f83-4d751bf854a6.png)

## Expected behaviour:

A user must be able to see the same properties of the installed plugin, e.g. see the link to the repo and be able to click on it.

**Comment by maraf** [comment]
I like it. It can also simplify displaying Release Notes (#11).
