### ISSUE TITLE
Filter out unsupported packages

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions.pluginmanager#61]
Git Extensions is being migrated to .NET, and many existing packages are targeting the old version of the app that runs on .NET Framework 4.6.1.
The new version of the Plugin Manager shows all known version, which is quite misleading:
![image](https://user-images.githubusercontent.com/4403806/141702692-e7a1edf7-92ed-439b-8821-663bdd7f14c3.png)

Consider how we can filter out (or render) unsupported packages.

Few ideas but nothing concrete, e.g.:
* filter based on the supported application's TFM (i.e. .NET 5.0)
* filter based on the supported version of https://github.com/gitextensions/gitextensions.extensibility

**Comment by maraf** [comment]
I think we should rely on `GitExtensions.Extensibility` version. Plugin manager has already a support for this, but it's turned-off since the initial release.

The down side is that we need to publish a new version of this package with Git Extensions release. From my experience, since we don't have a public API, my plugin needs an update with almost every Git Extensions feature update. But this raises a broader question of compatibility and also we may need to disable already installed plugins after update, etc.

Summary: both filtering based on dependency version and TFM are already supported. 
- TFM version would only need a small change here.
- `GitExtensions.Extensibility` version requires to publish that package.

**Comment by RussKie** [comment]
I believe we need to publish that package. And the app and  all plugins
must use that version.

Ultimately it needs to host all shared concerns. IIRC @ivangrek started
some work in that direction (but got stalled partially because I was
available to help and review in timely manner).

**Comment by ivangrek** [comment]
Perhaps we need to change the version for plugins in the main application and discard all plugins that have a lower version?

**Comment by RussKie** [comment]
Yes, I think that'd be the right move.

**Comment by maraf** [comment]
We should check and disable/uninstall plugins that are already installed, but doesn't fit in updated Git Extensions version, shouldn't we?

**Comment by ivangrek** [comment]
> We should check and disable/uninstall plugins that are already installed, but doesn't fit in updated Git Extensions version, shouldn't we?

I think something like this.

? AppPlaginVersion > PluginVersion : not load plugin

**Comment by maraf** [comment]
Yes, that is something I had in my mind too. 

But I think it requires to load nuspec info Git Extensions (where MEF is used) and determine whether the plugin fits in or not. There is currently no extension point for this.

**Comment by RussKie** [comment]
Can we inspect the dependency of a package? I.e., check if a plugin is dependent on a specific version (or a range) of GitExtensions.Extensibility, and install.

In the end of the day we can install any package, but the app will load only those supported... This issue is about improving the UX and making users aware what plugins are supported.

**Comment by maraf** [comment]
Yes, on a nuget level we can do that (and we are already doing that). What I am thinking about is how to check for compatibility on already installed plugins (after Git Extensions update). Because Git Extensions currently loads dlls from a folder. It doesn't know anything about nuget.

**Comment by RussKie** [comment]
I checked and we released v0.2 version of with .NET 5.0 support (https://github.com/gitextensions/gitextensions.extensibility/pull/21). Though we perhaps should have removed net461 support from it...
So I think we should all update to the latest version, and not filter out/visibly mark plugins that aren't built against [0.2.0, 0.3.0).

What do you think?

**Comment by maraf** [comment]
> Though we perhaps should have removed net461 support from it...

It would be better, but we probably can live with it.

> and not filter out/visibly mark

Is it what you wanted to say? Or did you mean "do filter out"? 🙂

**Comment by RussKie** [comment]
Typo ;) "do filter out"

**Comment by RussKie** [comment]
Here's a test build: https://ci.appveyor.com/api/buildjobs/2svhhdi4ank88rgg/artifacts/GitExtensions-4.0.0.13119-alpha-aabfaf14b.msi
