### ISSUE TITLE
Save last position and size

### ISSUE THREAD

**Issue by maraf** [gitextensions/gitextensions.pluginmanager#9]
Be careful with this one, this road is fraught with dangers.
In GE we have a number of issues in multi-monitor setups with dialog
windows shown outside visible area or on wrong monitor.

I thing that checking whether a loaded position and size are within boundaries of current displays could solve it.

**Comment by mast-eu** [comment]
Honestly, I think this one is not worth the trouble, at least for the moment.

Let's put it in the backlog and concentrate on the other issues first. We might get back to this later.
